### ISSUE TITLE
copy pasta

### ISSUE THREAD

**Issue by dolmation** [callumrawlinson/StaffList#1]
So I heard from a friend (VernoxMC) that my plugin had been copied word for word so I checked it out and turns out your oplist’s main file was copy and paste, which could have been a coincidence since it’s a really simple plugin, but something I noticed that guaranteed it was a copy paste was the part where it said 25 “-“s, that immediately showed me it was copy and pasted, but I was fine with it since VernoxMC had already gotten you to give credit and it’s a simple plugin anyways, but I looked through this one and saw the main file is literally a 100% copy and paste with a few things such as the names and file name changed, once again it’s a simple plugin but I ask you to not copy and paste without giving credit, if you had made the plugin fundamentally the exact same but you didn’t copy and paste I would be fine since you would have actually made it

**Comment by callumrawlinson** [comment]
whats your email! i will contact you there @dolmation

**Comment by callumrawlinson** [comment]
@dolmation hello please check the repo of mine again. it is now fixed
